spring:
    application:
        name: config-server
    profiles:
        active: native #it will automaticly use the native active profile
    
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/configurations
server:
    port: 8888
